"""Alembic version control for database migrations

Revision ID: 170c17b750f6
Revises: 23dd16df7c13
Create Date: 2025-12-14 10:01:25.401199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170c17b750f6'
down_revision = '23dd16df7c13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_number', sa.String(length=50), nullable=False),
    sa.Column('cashier_id', sa.UUID(), nullable=False),
    sa.Column('register_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'RECONCILED', name='shiftstatus', native_enum=False, length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_variance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_returns', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_exchanges', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('card_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('upi_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('other_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('opening_notes', sa.Text(), nullable=True),
    sa.Column('closing_notes', sa.Text(), nullable=True),
    sa.Column('reconciliation_notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('closing_cash IS NULL OR closing_cash >= 0', name='check_closing_cash_positive'),
    sa.CheckConstraint('opening_cash >= 0', name='check_opening_cash_positive'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cashier_shift_cashier', 'cashier_shifts', ['cashier_id'], unique=False)
    op.create_index('idx_cashier_shift_date', 'cashier_shifts', ['started_at'], unique=False)
    op.create_index('idx_cashier_shift_status', 'cashier_shifts', ['status'], unique=False)
    op.create_index(op.f('ix_cashier_shifts_cashier_id'), 'cashier_shifts', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_cashier_shifts_id'), 'cashier_shifts', ['id'], unique=False)
    op.create_index(op.f('ix_cashier_shifts_shift_number'), 'cashier_shifts', ['shift_number'], unique=True)
    op.create_table('cash_drawers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'BALANCED', 'OVER', 'SHORT', name='cashdrawerstatus', native_enum=False, length=50), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('denomination_breakdown', sa.JSON(), nullable=True),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_balance >= 0', name='check_drawer_balance_positive'),
    sa.ForeignKeyConstraint(['shift_id'], ['cashier_shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cash_drawer_shift', 'cash_drawers', ['shift_id'], unique=False)
    op.create_index('idx_cash_drawer_status', 'cash_drawers', ['status'], unique=False)
    op.create_index(op.f('ix_cash_drawers_id'), 'cash_drawers', ['id'], unique=False)
    op.create_index(op.f('ix_cash_drawers_shift_id'), 'cash_drawers', ['shift_id'], unique=False)
    op.create_table('pos_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.Enum('SALE', 'RETURN', 'EXCHANGE', 'REFUND', 'PAYOUT', 'CASH_IN', 'CASH_OUT', name='postransactiontype', native_enum=False, length=50), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('original_order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_generated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['cashier_shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_transaction_date', 'pos_transactions', ['transaction_at'], unique=False)
    op.create_index('idx_pos_transaction_shift', 'pos_transactions', ['shift_id'], unique=False)
    op.create_index('idx_pos_transaction_type', 'pos_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_pos_transactions_id'), 'pos_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_pos_transactions_order_id'), 'pos_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_pos_transactions_original_order_id'), 'pos_transactions', ['original_order_id'], unique=False)
    op.create_index(op.f('ix_pos_transactions_receipt_number'), 'pos_transactions', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_pos_transactions_shift_id'), 'pos_transactions', ['shift_id'], unique=False)
    op.create_index(op.f('ix_pos_transactions_transaction_at'), 'pos_transactions', ['transaction_at'], unique=False)
    op.create_index(op.f('ix_pos_transactions_transaction_number'), 'pos_transactions', ['transaction_number'], unique=True)
    op.create_table('return_exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('is_exchange', sa.Boolean(), nullable=False),
    sa.Column('original_order_id', sa.UUID(), nullable=False),
    sa.Column('new_order_id', sa.UUID(), nullable=True),
    sa.Column('pos_transaction_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('DEFECTIVE', 'WRONG_SIZE', 'WRONG_COLOR', 'CHANGED_MIND', 'NOT_AS_EXPECTED', 'DAMAGED', 'OTHER', name='returnreason', native_enum=False, length=50), nullable=False),
    sa.Column('reason_description', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('restocking_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('processed_by_id', sa.UUID(), nullable=False),
    sa.Column('restocked', sa.Boolean(), nullable=False),
    sa.Column('returned_items', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('refund_amount >= 0', name='check_refund_amount_positive'),
    sa.CheckConstraint('restocking_fee >= 0', name='check_restocking_fee_positive'),
    sa.ForeignKeyConstraint(['new_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pos_transaction_id'], ['pos_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_return_exchange_date', 'return_exchanges', ['returned_at'], unique=False)
    op.create_index('idx_return_exchange_original_order', 'return_exchanges', ['original_order_id'], unique=False)
    op.create_index(op.f('ix_return_exchanges_id'), 'return_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_return_exchanges_new_order_id'), 'return_exchanges', ['new_order_id'], unique=False)
    op.create_index(op.f('ix_return_exchanges_original_order_id'), 'return_exchanges', ['original_order_id'], unique=False)
    op.create_index(op.f('ix_return_exchanges_pos_transaction_id'), 'return_exchanges', ['pos_transaction_id'], unique=False)
    op.create_index(op.f('ix_return_exchanges_return_number'), 'return_exchanges', ['return_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_exchanges_return_number'), table_name='return_exchanges')
    op.drop_index(op.f('ix_return_exchanges_pos_transaction_id'), table_name='return_exchanges')
    op.drop_index(op.f('ix_return_exchanges_original_order_id'), table_name='return_exchanges')
    op.drop_index(op.f('ix_return_exchanges_new_order_id'), table_name='return_exchanges')
    op.drop_index(op.f('ix_return_exchanges_id'), table_name='return_exchanges')
    op.drop_index('idx_return_exchange_original_order', table_name='return_exchanges')
    op.drop_index('idx_return_exchange_date', table_name='return_exchanges')
    op.drop_table('return_exchanges')
    op.drop_index(op.f('ix_pos_transactions_transaction_number'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_transaction_at'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_shift_id'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_receipt_number'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_original_order_id'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_order_id'), table_name='pos_transactions')
    op.drop_index(op.f('ix_pos_transactions_id'), table_name='pos_transactions')
    op.drop_index('idx_pos_transaction_type', table_name='pos_transactions')
    op.drop_index('idx_pos_transaction_shift', table_name='pos_transactions')
    op.drop_index('idx_pos_transaction_date', table_name='pos_transactions')
    op.drop_table('pos_transactions')
    op.drop_index(op.f('ix_cash_drawers_shift_id'), table_name='cash_drawers')
    op.drop_index(op.f('ix_cash_drawers_id'), table_name='cash_drawers')
    op.drop_index('idx_cash_drawer_status', table_name='cash_drawers')
    op.drop_index('idx_cash_drawer_shift', table_name='cash_drawers')
    op.drop_table('cash_drawers')
    op.drop_index(op.f('ix_cashier_shifts_shift_number'), table_name='cashier_shifts')
    op.drop_index(op.f('ix_cashier_shifts_id'), table_name='cashier_shifts')
    op.drop_index(op.f('ix_cashier_shifts_cashier_id'), table_name='cashier_shifts')
    op.drop_index('idx_cashier_shift_status', table_name='cashier_shifts')
    op.drop_index('idx_cashier_shift_date', table_name='cashier_shifts')
    op.drop_index('idx_cashier_shift_cashier', table_name='cashier_shifts')
    op.drop_table('cashier_shifts')
    # ### end Alembic commands ###
