"""Alembic version control for database migrations

Revision ID: 23dd16df7c13
Revises: b3cb6ef962b3
Create Date: 2025-12-14 09:43:35.907909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dd16df7c13'
down_revision = 'b3cb6ef962b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wholesale_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_legal_name', sa.String(length=255), nullable=True),
    sa.Column('business_registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.Enum('RETAILER', 'DISTRIBUTOR', 'WHOLESALER', 'MANUFACTURER', 'EXPORTER', 'ECOMMERCE', name='customertype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', 'REJECTED', 'CLOSED', name='customerstatus', native_enum=False, length=50), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=False),
    sa.Column('primary_email', sa.String(length=255), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('secondary_email', sa.String(length=255), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('billing_address_line1', sa.String(length=255), nullable=False),
    sa.Column('billing_address_line2', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=False),
    sa.Column('billing_state', sa.String(length=100), nullable=False),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=False),
    sa.Column('billing_country', sa.String(length=100), nullable=False),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=100), nullable=True),
    sa.Column('shipping_postal_code', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_used', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_available', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_status', sa.Enum('GOOD', 'WARNING', 'EXCEEDED', 'SUSPENDED', name='creditstatus', native_enum=False, length=50), nullable=False),
    sa.Column('payment_terms', sa.Enum('IMMEDIATE', 'NET_7', 'NET_15', 'NET_30', 'NET_60', 'NET_90', 'COD', 'ADVANCE', name='paymentterms', native_enum=False, length=50), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('default_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('has_contract_pricing', sa.Boolean(), nullable=False),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_order_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sales_rep_id', sa.UUID(), nullable=True),
    sa.Column('business_since', sa.Date(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('number_of_stores', sa.Integer(), nullable=True),
    sa.Column('preferred_shipping_method', sa.String(length=100), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_orders', sa.Boolean(), nullable=False),
    sa.Column('send_invoices_via_email', sa.Boolean(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('credit_limit >= 0', name='check_credit_limit_positive'),
    sa.CheckConstraint('credit_used >= 0', name='check_credit_used_positive'),
    sa.CheckConstraint('default_discount_percentage >= 0 AND default_discount_percentage <= 100', name='check_discount_percentage_range'),
    sa.CheckConstraint('minimum_order_quantity >= 0', name='check_moq_positive'),
    sa.CheckConstraint('minimum_order_value >= 0', name='check_mov_positive'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_registration_number')
    )
    op.create_index('idx_wholesale_customer_company', 'wholesale_customers', ['company_name'], unique=False)
    op.create_index('idx_wholesale_customer_credit_status', 'wholesale_customers', ['credit_status'], unique=False)
    op.create_index('idx_wholesale_customer_sales_rep', 'wholesale_customers', ['sales_rep_id'], unique=False)
    op.create_index('idx_wholesale_customer_status', 'wholesale_customers', ['status'], unique=False)
    op.create_index(op.f('ix_wholesale_customers_company_name'), 'wholesale_customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_wholesale_customers_id'), 'wholesale_customers', ['id'], unique=False)
    op.create_index(op.f('ix_wholesale_customers_primary_email'), 'wholesale_customers', ['primary_email'], unique=False)
    op.create_index(op.f('ix_wholesale_customers_sales_rep_id'), 'wholesale_customers', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_wholesale_customers_tax_id'), 'wholesale_customers', ['tax_id'], unique=False)
    op.create_table('contract_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_quantity', sa.Integer(), nullable=False),
    sa.Column('maximum_quantity', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('contract_price >= 0', name='check_contract_price_positive'),
    sa.CheckConstraint('discount_percentage IS NULL OR (discount_percentage >= 0 AND discount_percentage <= 100)', name='check_contract_discount_range'),
    sa.CheckConstraint('maximum_quantity IS NULL OR maximum_quantity >= minimum_quantity', name='check_quantity_range_valid'),
    sa.CheckConstraint('minimum_quantity > 0', name='check_minimum_quantity_positive'),
    sa.CheckConstraint('valid_until >= valid_from', name='check_validity_period'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['wholesale_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_pricing_active', 'contract_pricing', ['is_active'], unique=False)
    op.create_index('idx_contract_pricing_category', 'contract_pricing', ['category_id'], unique=False)
    op.create_index('idx_contract_pricing_customer', 'contract_pricing', ['customer_id'], unique=False)
    op.create_index('idx_contract_pricing_product', 'contract_pricing', ['product_variant_id'], unique=False)
    op.create_index('idx_contract_pricing_validity', 'contract_pricing', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_contract_pricing_category_id'), 'contract_pricing', ['category_id'], unique=False)
    op.create_index(op.f('ix_contract_pricing_customer_id'), 'contract_pricing', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contract_pricing_id'), 'contract_pricing', ['id'], unique=False)
    op.create_index(op.f('ix_contract_pricing_product_variant_id'), 'contract_pricing', ['product_variant_id'], unique=False)
    op.add_column('orders', sa.Column('wholesale_customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_orders_wholesale_customer_id'), 'orders', ['wholesale_customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'wholesale_customers', ['wholesale_customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_wholesale_customer_id'), table_name='orders')
    op.drop_column('orders', 'wholesale_customer_id')
    op.drop_index(op.f('ix_contract_pricing_product_variant_id'), table_name='contract_pricing')
    op.drop_index(op.f('ix_contract_pricing_id'), table_name='contract_pricing')
    op.drop_index(op.f('ix_contract_pricing_customer_id'), table_name='contract_pricing')
    op.drop_index(op.f('ix_contract_pricing_category_id'), table_name='contract_pricing')
    op.drop_index('idx_contract_pricing_validity', table_name='contract_pricing')
    op.drop_index('idx_contract_pricing_product', table_name='contract_pricing')
    op.drop_index('idx_contract_pricing_customer', table_name='contract_pricing')
    op.drop_index('idx_contract_pricing_category', table_name='contract_pricing')
    op.drop_index('idx_contract_pricing_active', table_name='contract_pricing')
    op.drop_table('contract_pricing')
    op.drop_index(op.f('ix_wholesale_customers_tax_id'), table_name='wholesale_customers')
    op.drop_index(op.f('ix_wholesale_customers_sales_rep_id'), table_name='wholesale_customers')
    op.drop_index(op.f('ix_wholesale_customers_primary_email'), table_name='wholesale_customers')
    op.drop_index(op.f('ix_wholesale_customers_id'), table_name='wholesale_customers')
    op.drop_index(op.f('ix_wholesale_customers_company_name'), table_name='wholesale_customers')
    op.drop_index('idx_wholesale_customer_status', table_name='wholesale_customers')
    op.drop_index('idx_wholesale_customer_sales_rep', table_name='wholesale_customers')
    op.drop_index('idx_wholesale_customer_credit_status', table_name='wholesale_customers')
    op.drop_index('idx_wholesale_customer_company', table_name='wholesale_customers')
    op.drop_table('wholesale_customers')
    # ### end Alembic commands ###
