"""Alembic version control for database migrations

Revision ID: b3cb6ef962b3
Revises: g12345678abc
Create Date: 2025-12-14 09:31:01.800679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cb6ef962b3'
down_revision = 'g12345678abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier_type', sa.Enum('QUANTITY', 'VALUE', 'CUSTOMER', 'SEASONAL', name='pricingtiertype'), nullable=False),
    sa.Column('channel', sa.Enum('WHOLESALE', 'RETAIL', 'ECOMMERCE', 'MARKETPLACE', name='saleschannel'), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fixed_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('category_ids', sa.JSON(), nullable=True),
    sa.Column('customer_ids', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_tiers_channel'), 'pricing_tiers', ['channel'], unique=False)
    op.create_index(op.f('ix_pricing_tiers_code'), 'pricing_tiers', ['code'], unique=True)
    op.create_index(op.f('ix_pricing_tiers_id'), 'pricing_tiers', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_tiers_is_active'), 'pricing_tiers', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_tiers_tier_type'), 'pricing_tiers', ['tier_type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('WHOLESALE', 'RETAIL', 'ECOMMERCE', 'MARKETPLACE', name='saleschannel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'CONFIRMED', 'PROCESSING', 'READY_TO_SHIP', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'RETURN_REQUESTED', 'RETURNED', 'FAILED', name='orderstatus'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('sales_rep_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_code', sa.String(length=50), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shipping_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'PARTIAL', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'NET_BANKING', 'WALLET', 'CHEQUE', 'BANK_TRANSFER', 'CREDIT', 'COD', name='paymentmethod'), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('payment_due_date', sa.DateTime(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_customer_date', 'orders', ['customer_id', 'order_date'], unique=False)
    op.create_index('idx_order_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('idx_order_status_channel', 'orders', ['status', 'channel'], unique=False)
    op.create_index(op.f('ix_orders_channel'), 'orders', ['channel'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_sales_rep_id'), 'orders', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'NET_BANKING', 'WALLET', 'CHEQUE', 'BANK_TRANSFER', 'CREDIT', 'COD', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'PARTIAL', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_date', sa.DateTime(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_method'), 'payment_transactions', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_status'), 'payment_transactions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_date'), 'payment_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_id'), 'payment_transactions', ['transaction_id'], unique=True)
    op.create_table('shipping_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('shipping_status', sa.Enum('PENDING', 'PREPARING', 'READY_TO_SHIP', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RETURNED', name='shippingstatus'), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('shipping_method', sa.String(length=100), nullable=False),
    sa.Column('shipping_carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('delivered_to', sa.String(length=200), nullable=True),
    sa.Column('delivery_signature_url', sa.String(length=500), nullable=True),
    sa.Column('delivery_photo_url', sa.String(length=500), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_details_id'), 'shipping_details', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_details_order_id'), 'shipping_details', ['order_id'], unique=True)
    op.create_index(op.f('ix_shipping_details_shipping_status'), 'shipping_details', ['shipping_status'], unique=False)
    op.create_index(op.f('ix_shipping_details_tracking_number'), 'shipping_details', ['tracking_number'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('variant_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_variant_id'), 'order_items', ['product_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_shipping_details_tracking_number'), table_name='shipping_details')
    op.drop_index(op.f('ix_shipping_details_shipping_status'), table_name='shipping_details')
    op.drop_index(op.f('ix_shipping_details_order_id'), table_name='shipping_details')
    op.drop_index(op.f('ix_shipping_details_id'), table_name='shipping_details')
    op.drop_table('shipping_details')
    op.drop_index(op.f('ix_payment_transactions_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_transaction_date'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_method'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_sales_rep_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_channel'), table_name='orders')
    op.drop_index('idx_order_status_channel', table_name='orders')
    op.drop_index('idx_order_payment_status', table_name='orders')
    op.drop_index('idx_order_customer_date', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_pricing_tiers_tier_type'), table_name='pricing_tiers')
    op.drop_index(op.f('ix_pricing_tiers_is_active'), table_name='pricing_tiers')
    op.drop_index(op.f('ix_pricing_tiers_id'), table_name='pricing_tiers')
    op.drop_index(op.f('ix_pricing_tiers_code'), table_name='pricing_tiers')
    op.drop_index(op.f('ix_pricing_tiers_channel'), table_name='pricing_tiers')
    op.drop_table('pricing_tiers')
    # ### end Alembic commands ###
