"""Alembic version control for database migrations

Revision ID: d9d7f43815fe
Revises: c93eb4f5cc87
Create Date: 2025-12-14 10:16:18.878999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d7f43815fe'
down_revision = 'c93eb4f5cc87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promo_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_SHIPPING', 'BUY_X_GET_Y', name='promocodetype', native_enum=False, length=50), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('minimum_order_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('maximum_discount_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_per_customer', sa.Integer(), nullable=True),
    sa.Column('current_usage_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'EXHAUSTED', name='promocodestatus', native_enum=False, length=50), nullable=False),
    sa.Column('applicable_categories', sa.JSON(), nullable=True),
    sa.Column('applicable_products', sa.JSON(), nullable=True),
    sa.Column('excluded_products', sa.JSON(), nullable=True),
    sa.Column('customer_emails', sa.JSON(), nullable=True),
    sa.Column('new_customers_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_usage_count >= 0', name='check_promo_usage_count_positive'),
    sa.CheckConstraint('discount_amount IS NULL OR discount_amount >= 0', name='check_promo_discount_amount_positive'),
    sa.CheckConstraint('discount_percentage IS NULL OR (discount_percentage >= 0 AND discount_percentage <= 100)', name='check_promo_discount_percentage_range'),
    sa.CheckConstraint('minimum_order_value IS NULL OR minimum_order_value >= 0', name='check_promo_min_order_positive'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit > 0', name='check_promo_usage_limit_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promo_code_code', 'promo_codes', ['code'], unique=False)
    op.create_index('idx_promo_code_status', 'promo_codes', ['status'], unique=False)
    op.create_index('idx_promo_code_validity', 'promo_codes', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_id'), 'promo_codes', ['id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wishlist_user', 'wishlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_index(op.f('ix_wishlists_user_id'), 'wishlists', ['user_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', name='reviewstatus', native_enum=False, length=50), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), nullable=False),
    sa.Column('moderator_notes', sa.Text(), nullable=True),
    sa.Column('moderated_by_id', sa.UUID(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('helpful_count >= 0', name='check_helpful_count_positive'),
    sa.CheckConstraint('not_helpful_count >= 0', name='check_not_helpful_count_positive'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_review_rating_range'),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_review_rating', 'product_reviews', ['rating'], unique=False)
    op.create_index('idx_product_review_status', 'product_reviews', ['status'], unique=False)
    op.create_index('idx_product_review_user', 'product_reviews', ['user_id'], unique=False)
    op.create_index('idx_product_review_variant', 'product_reviews', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_id'), 'product_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_product_reviews_order_id'), 'product_reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_variant_id'), 'product_reviews', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.create_table('promo_code_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='check_promo_usage_discount_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promo_usage_order', 'promo_code_usages', ['order_id'], unique=False)
    op.create_index('idx_promo_usage_promo', 'promo_code_usages', ['promo_code_id'], unique=False)
    op.create_index('idx_promo_usage_user', 'promo_code_usages', ['user_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_id'), 'promo_code_usages', ['id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_order_id'), 'promo_code_usages', ['order_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_promo_code_id'), 'promo_code_usages', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_user_id'), 'promo_code_usages', ['user_id'], unique=False)
    op.create_table('shopping_carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ABANDONED', 'CONVERTED', 'MERGED', name='cartstatus', native_enum=False, length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shopping_cart_activity', 'shopping_carts', ['last_activity_at'], unique=False)
    op.create_index('idx_shopping_cart_session', 'shopping_carts', ['session_id'], unique=False)
    op.create_index('idx_shopping_cart_status', 'shopping_carts', ['status'], unique=False)
    op.create_index('idx_shopping_cart_user', 'shopping_carts', ['user_id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_id'), 'shopping_carts', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_order_id'), 'shopping_carts', ['order_id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_session_id'), 'shopping_carts', ['session_id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_user_id'), 'shopping_carts', ['user_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wishlist_item_variant', 'wishlist_items', ['product_variant_id'], unique=False)
    op.create_index('idx_wishlist_item_wishlist', 'wishlist_items', ['wishlist_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_id'), 'wishlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_product_variant_id'), 'wishlist_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_wishlist_id'), 'wishlist_items', ['wishlist_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_cart_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='check_cart_item_price_positive'),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cart_item_cart', 'cart_items', ['cart_id'], unique=False)
    op.create_index('idx_cart_item_variant', 'cart_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_variant_id'), 'cart_items', ['product_variant_id'], unique=False)
    op.drop_index('ix_product_variants_color_id', table_name='product_variants')
    op.drop_constraint('fk_product_variants_color_id', 'product_variants', type_='foreignkey')
    op.drop_column('product_variants', 'color_id')
    op.drop_index('ix_products_collection_id', table_name='products')
    op.drop_index('ix_products_size_chart_id', table_name='products')
    op.drop_index('ix_products_style_id', table_name='products')
    op.drop_constraint('fk_products_size_chart_id', 'products', type_='foreignkey')
    op.drop_constraint('fk_products_collection_id', 'products', type_='foreignkey')
    op.drop_constraint('fk_products_style_id', 'products', type_='foreignkey')
    op.drop_column('products', 'collection_id')
    op.drop_column('products', 'style_id')
    op.drop_column('products', 'size_chart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size_chart_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('style_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_products_style_id', 'products', 'styles', ['style_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_products_collection_id', 'products', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_products_size_chart_id', 'products', 'size_charts', ['size_chart_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_products_style_id', 'products', ['style_id'], unique=False)
    op.create_index('ix_products_size_chart_id', 'products', ['size_chart_id'], unique=False)
    op.create_index('ix_products_collection_id', 'products', ['collection_id'], unique=False)
    op.add_column('product_variants', sa.Column('color_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_product_variants_color_id', 'product_variants', 'colors', ['color_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_product_variants_color_id', 'product_variants', ['color_id'], unique=False)
    op.drop_index(op.f('ix_cart_items_product_variant_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_index('idx_cart_item_variant', table_name='cart_items')
    op.drop_index('idx_cart_item_cart', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_wishlist_items_wishlist_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_product_variant_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.drop_index('idx_wishlist_item_wishlist', table_name='wishlist_items')
    op.drop_index('idx_wishlist_item_variant', table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_shopping_carts_user_id'), table_name='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_session_id'), table_name='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_order_id'), table_name='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_id'), table_name='shopping_carts')
    op.drop_index('idx_shopping_cart_user', table_name='shopping_carts')
    op.drop_index('idx_shopping_cart_status', table_name='shopping_carts')
    op.drop_index('idx_shopping_cart_session', table_name='shopping_carts')
    op.drop_index('idx_shopping_cart_activity', table_name='shopping_carts')
    op.drop_table('shopping_carts')
    op.drop_index(op.f('ix_promo_code_usages_user_id'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_promo_code_id'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_order_id'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_id'), table_name='promo_code_usages')
    op.drop_index('idx_promo_usage_user', table_name='promo_code_usages')
    op.drop_index('idx_promo_usage_promo', table_name='promo_code_usages')
    op.drop_index('idx_promo_usage_order', table_name='promo_code_usages')
    op.drop_table('promo_code_usages')
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_variant_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_order_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_id'), table_name='product_reviews')
    op.drop_index('idx_product_review_variant', table_name='product_reviews')
    op.drop_index('idx_product_review_user', table_name='product_reviews')
    op.drop_index('idx_product_review_status', table_name='product_reviews')
    op.drop_index('idx_product_review_rating', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('ix_wishlists_user_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_index('idx_wishlist_user', table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_promo_codes_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_index('idx_promo_code_validity', table_name='promo_codes')
    op.drop_index('idx_promo_code_status', table_name='promo_codes')
    op.drop_index('idx_promo_code_code', table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
