"""Alembic version control for database migrations

Revision ID: dbd86207331b
Revises: f00eda7af84d
Create Date: 2025-12-13 23:08:02.018507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd86207331b'
down_revision = 'f00eda7af84d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_display_order'), 'brands', ['display_order'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index('ix_brands_name_active', 'brands', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_display_order'), 'categories', ['display_order'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index('ix_categories_parent_active', 'categories', ['parent_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index('ix_categories_slug_active', 'categories', ['slug', 'is_active'], unique=False)
    op.create_table('stock_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_code_active', 'stock_locations', ['code', 'is_active'], unique=False)
    op.create_index('ix_locations_type_active', 'stock_locations', ['location_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_stock_locations_code'), 'stock_locations', ['code'], unique=True)
    op.create_index(op.f('ix_stock_locations_id'), 'stock_locations', ['id'], unique=False)
    op.create_index(op.f('ix_stock_locations_is_active'), 'stock_locations', ['is_active'], unique=False)
    op.create_index(op.f('ix_stock_locations_location_type'), 'stock_locations', ['location_type'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('business_registration', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index('ix_suppliers_code_active', 'suppliers', ['code', 'is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index('ix_suppliers_name_active', 'suppliers', ['name', 'is_active'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=350), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('garment_type', sa.String(length=100), nullable=True),
    sa.Column('fabric_type', sa.String(length=200), nullable=True),
    sa.Column('fabric_composition', sa.String(length=500), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('collection', sa.String(length=200), nullable=True),
    sa.Column('base_cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_retail_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_wholesale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_category', sa.String(length=100), nullable=True),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('allow_backorder', sa.Boolean(), nullable=False),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('measurement_unit', sa.String(length=50), nullable=True),
    sa.Column('measurements', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_new_arrival', sa.Boolean(), nullable=False),
    sa.Column('is_on_sale', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_brand_active', 'products', ['brand_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_category_active', 'products', ['category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_featured', 'products', ['is_featured', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_is_new_arrival'), 'products', ['is_new_arrival'], unique=False)
    op.create_index(op.f('ix_products_is_on_sale'), 'products', ['is_on_sale'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index('ix_products_sku_active', 'products', ['sku', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('variant_attributes', sa.JSON(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('wholesale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimension_unit', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_variants_color'), 'product_variants', ['color'], unique=False)
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_size'), 'product_variants', ['size'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_index('ix_variants_product_active', 'product_variants', ['product_id', 'is_active'], unique=False)
    op.create_index('ix_variants_size_color', 'product_variants', ['size', 'color', 'is_active'], unique=False)
    op.create_index('ix_variants_sku_active', 'product_variants', ['sku', 'is_active'], unique=False)
    op.create_table('inventory_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('max_stock_level', sa.Integer(), nullable=True),
    sa.Column('last_counted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_available', 'inventory_levels', ['quantity_available'], unique=False)
    op.create_index(op.f('ix_inventory_levels_id'), 'inventory_levels', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_location_id'), 'inventory_levels', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_product_variant_id'), 'inventory_levels', ['product_variant_id'], unique=False)
    op.create_index('ix_inventory_low_stock', 'inventory_levels', ['quantity_available', 'reorder_point'], unique=False)
    op.create_index('ix_inventory_variant_location', 'inventory_levels', ['product_variant_id', 'location_id'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'TRANSFER', 'ADJUSTMENT', 'RETURN', 'RETURN_TO_SUPPLIER', 'DAMAGE', 'LOSS', 'PRODUCTION', 'CONSUMPTION', name='movementtype', native_enum=False, length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['stock_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['stock_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_from_location_id'), 'inventory_movements', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_date'), 'inventory_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_variant_id'), 'inventory_movements', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_id'), 'inventory_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_number'), 'inventory_movements', ['reference_number'], unique=False)
    op.create_index(op.f('ix_inventory_movements_to_location_id'), 'inventory_movements', ['to_location_id'], unique=False)
    op.create_index('ix_movements_reference', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_movements_type_date', 'inventory_movements', ['movement_type', 'movement_date'], unique=False)
    op.create_index('ix_movements_variant_date', 'inventory_movements', ['product_variant_id', 'movement_date'], unique=False)
    op.create_table('low_stock_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('recommended_order_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('alert_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_status_date', 'low_stock_alerts', ['status', 'alert_date'], unique=False)
    op.create_index('ix_alerts_variant_location', 'low_stock_alerts', ['product_variant_id', 'location_id'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_alert_date'), 'low_stock_alerts', ['alert_date'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_id'), 'low_stock_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_location_id'), 'low_stock_alerts', ['location_id'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_product_variant_id'), 'low_stock_alerts', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_status'), 'low_stock_alerts', ['status'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_number', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('adjustment_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('adjusted_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('adjustment_date', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adjustments_location_date', 'stock_adjustments', ['location_id', 'adjustment_date'], unique=False)
    op.create_index('ix_adjustments_status', 'stock_adjustments', ['status', 'adjustment_date'], unique=False)
    op.create_index('ix_adjustments_variant_date', 'stock_adjustments', ['product_variant_id', 'adjustment_date'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_adjustment_date'), 'stock_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_adjustment_number'), 'stock_adjustments', ['adjustment_number'], unique=True)
    op.create_index(op.f('ix_stock_adjustments_id'), 'stock_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_location_id'), 'stock_adjustments', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_product_variant_id'), 'stock_adjustments', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_status'), 'stock_adjustments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_adjustments_status'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_product_variant_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_location_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_adjustment_number'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_adjustment_date'), table_name='stock_adjustments')
    op.drop_index('ix_adjustments_variant_date', table_name='stock_adjustments')
    op.drop_index('ix_adjustments_status', table_name='stock_adjustments')
    op.drop_index('ix_adjustments_location_date', table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index(op.f('ix_low_stock_alerts_status'), table_name='low_stock_alerts')
    op.drop_index(op.f('ix_low_stock_alerts_product_variant_id'), table_name='low_stock_alerts')
    op.drop_index(op.f('ix_low_stock_alerts_location_id'), table_name='low_stock_alerts')
    op.drop_index(op.f('ix_low_stock_alerts_id'), table_name='low_stock_alerts')
    op.drop_index(op.f('ix_low_stock_alerts_alert_date'), table_name='low_stock_alerts')
    op.drop_index('ix_alerts_variant_location', table_name='low_stock_alerts')
    op.drop_index('ix_alerts_status_date', table_name='low_stock_alerts')
    op.drop_table('low_stock_alerts')
    op.drop_index('ix_movements_variant_date', table_name='inventory_movements')
    op.drop_index('ix_movements_type_date', table_name='inventory_movements')
    op.drop_index('ix_movements_reference', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_to_location_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_number'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_variant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_date'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_from_location_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_inventory_variant_location', table_name='inventory_levels')
    op.drop_index('ix_inventory_low_stock', table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_product_variant_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_location_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_id'), table_name='inventory_levels')
    op.drop_index('ix_inventory_available', table_name='inventory_levels')
    op.drop_table('inventory_levels')
    op.drop_index('ix_variants_sku_active', table_name='product_variants')
    op.drop_index('ix_variants_size_color', table_name='product_variants')
    op.drop_index('ix_variants_product_active', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_size'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_color'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index('ix_products_sku_active', table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_is_on_sale'), table_name='products')
    op.drop_index(op.f('ix_products_is_new_arrival'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('ix_products_featured', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('ix_products_category_active', table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index('ix_products_brand_active', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_suppliers_name_active', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_code_active', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_stock_locations_location_type'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_is_active'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_id'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_code'), table_name='stock_locations')
    op.drop_index('ix_locations_type_active', table_name='stock_locations')
    op.drop_index('ix_locations_code_active', table_name='stock_locations')
    op.drop_table('stock_locations')
    op.drop_index('ix_categories_slug_active', table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index('ix_categories_parent_active', table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_display_order'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index('ix_brands_name_active', table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_display_order'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
